
import java.awt.Color;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ayupe
 */
public class NewJFrame extends javax.swing.JFrame {
    int xx, xy;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        AlgoPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        cariKuadrat_btn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bubblesort_btn = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        bubblesort_algo = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tfAngka = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        tfHasil = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        tfTotalAngka = new javax.swing.JTextField();
        eucledian = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        tfNilai1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        tfNilai2 = new javax.swing.JTextField();
        btnSubmit2 = new javax.swing.JButton();
        btnClear2 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        tfNilai11 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        tfNilai22 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        tfHasil2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        cariKuadrat = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        barisPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelBarisDeret = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        btnBarisAritmatika1 = new javax.swing.JButton();
        btnBarisAritmatika2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jButton18 = new javax.swing.JButton();
        brAritmatika = new javax.swing.JPanel();
        PanelBarisDeret1 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        tfHasilnya = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        tfNilai = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        tfBeda = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        tfElemen = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        drAritmatika = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        PanelBarisDeret2 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel65 = new javax.swing.JLabel();
        tfHasilnya1 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        tfNilai3 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        tfBeda1 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        tfElemen1 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        probabilitasPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        tfJumlahKejadian = new javax.swing.JTextField();
        tfJumlahPercobaan1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnHitung = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tfHasilPrb = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        btnHitung1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        profilPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jButton15 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setBackground(new java.awt.Color(35, 67, 163));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MATH APP");
        dashboard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 15));
        dashboard.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 10));

        jPanel3.setBackground(new java.awt.Color(88, 122, 224));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Algoritma");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(14, 14, 14))
        );

        dashboard.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 50));

        jPanel6.setBackground(new java.awt.Color(77, 108, 202));
        jPanel6.setToolTipText("");
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Baris dan Deret");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dashboard.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 50));

        jPanel7.setBackground(new java.awt.Color(77, 108, 202));
        jPanel7.setToolTipText("");
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Probabilitas");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        dashboard.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, 50));

        jPanel8.setBackground(new java.awt.Color(77, 108, 202));
        jPanel8.setToolTipText("");
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Profil");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        dashboard.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, 50));

        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 420));

        AlgoPanel.setBackground(new java.awt.Color(255, 255, 255));
        AlgoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        AlgoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("QUIT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        AlgoPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 100, -1));

        cariKuadrat_btn.setBackground(new java.awt.Color(255, 153, 153));
        cariKuadrat_btn.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        cariKuadrat_btn.setForeground(new java.awt.Color(255, 255, 255));
        cariKuadrat_btn.setText("Mencari Kuadrat");
        cariKuadrat_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cariKuadrat_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cariKuadrat_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cariKuadrat_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariKuadrat_btnActionPerformed(evt);
            }
        });
        AlgoPanel.add(cariKuadrat_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, 50));

        jButton5.setBackground(new java.awt.Color(0, 153, 255));
        jButton5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Algoritma Eucledian");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setIconTextGap(20);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        AlgoPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, 50));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Menu Algoritma");
        AlgoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Algoritma merupakan prosedur yang mengikuti serangkaian langkah");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("yang sistematis merngarah pada jawaban yang diinginkan.");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ALGORITMA MATEMATIKA DISKRIT");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        AlgoPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));

        bubblesort_btn.setBackground(new java.awt.Color(0, 204, 204));
        bubblesort_btn.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        bubblesort_btn.setForeground(new java.awt.Color(255, 255, 255));
        bubblesort_btn.setText("Bubble Sort");
        bubblesort_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bubblesort_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubblesort_btn.setIconTextGap(20);
        bubblesort_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubblesort_btnActionPerformed(evt);
            }
        });
        AlgoPanel.add(bubblesort_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 50));

        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        AlgoPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/output-onlinepngtools (3).png"))); // NOI18N
        AlgoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 152, 180, 200));

        getContentPane().add(AlgoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 500, 420));

        bubblesort_algo.setBackground(new java.awt.Color(255, 255, 255));
        bubblesort_algo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        bubblesort_algo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(255, 0, 51));
        jButton8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("QUIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        bubblesort_algo.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 90, -1));

        jPanel11.setBackground(new java.awt.Color(255, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Algoritma pengurutan data yang menggunakan metode perbandingan");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 20));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("untuk menyusun elemen dalam urutan menaik atau menurun");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("BUBBLESORT");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        bubblesort_algo.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));

        tfAngka.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        tfAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAngkaActionPerformed(evt);
            }
        });
        bubblesort_algo.add(tfAngka, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 360, 40));

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel28.setText("Masukkan angka yang akan di urutkan :");
        bubblesort_algo.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        btnSubmit.setBackground(new java.awt.Color(255, 102, 102));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        bubblesort_algo.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        btnClear.setBackground(new java.awt.Color(255, 0, 102));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        bubblesort_algo.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel29.setText("Hasil angka yang sudah diurutkan");
        bubblesort_algo.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        tfHasil.setEditable(false);
        tfHasil.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        tfHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHasilActionPerformed(evt);
            }
        });
        bubblesort_algo.add(tfHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 340, 30));
        bubblesort_algo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 470, 10));

        jLabel30.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel30.setText("Total angka yang diurutkan");
        bubblesort_algo.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        tfTotalAngka.setEditable(false);
        tfTotalAngka.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        tfTotalAngka.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bubblesort_algo.add(tfTotalAngka, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 90, 40));

        getContentPane().add(bubblesort_algo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 500, 420));

        eucledian.setBackground(new java.awt.Color(255, 255, 255));
        eucledian.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        eucledian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(0, 204, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Algoritma merupakan prosedur yang mengikuti serangkaian langkah");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 20));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("yang sistematis merngarah pada jawaban yang diinginkan.");
        jPanel12.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Algoritma Eucledian");
        jPanel12.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        eucledian.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));
        eucledian.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 470, 10));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel24.setText("Masukkan nilai pertama");
        eucledian.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        tfNilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNilai1ActionPerformed(evt);
            }
        });
        eucledian.add(tfNilai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 80, 40));

        jLabel37.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel37.setText("Masukkan nilai kedua");
        eucledian.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        tfNilai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNilai2ActionPerformed(evt);
            }
        });
        eucledian.add(tfNilai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 80, 40));

        btnSubmit2.setBackground(new java.awt.Color(0, 204, 204));
        btnSubmit2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmit2.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit2.setText("Submit");
        btnSubmit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit2ActionPerformed(evt);
            }
        });
        eucledian.add(btnSubmit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 80, -1));

        btnClear2.setBackground(new java.awt.Color(153, 0, 51));
        btnClear2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear2.setForeground(new java.awt.Color(255, 255, 255));
        btnClear2.setText("Clear");
        btnClear2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });
        eucledian.add(btnClear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 80, -1));

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel38.setText("Hasil FPB dari");
        eucledian.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        tfNilai11.setEditable(false);
        tfNilai11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNilai11ActionPerformed(evt);
            }
        });
        eucledian.add(tfNilai11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 70, 30));

        jLabel39.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel39.setText("dan");
        eucledian.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        tfNilai22.setEditable(false);
        tfNilai22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNilai22ActionPerformed(evt);
            }
        });
        eucledian.add(tfNilai22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 70, 30));

        jLabel40.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel40.setText("adalah");
        eucledian.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        tfHasil2.setEditable(false);
        tfHasil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHasil2ActionPerformed(evt);
            }
        });
        eucledian.add(tfHasil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 70, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("QUIT");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        eucledian.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 100, -1));

        getContentPane().add(eucledian, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 500, 420));

        cariKuadrat.setBackground(new java.awt.Color(255, 255, 255));
        cariKuadrat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        cariKuadrat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(224, 119, 50));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Algoritma merupakan prosedur yang mengikuti serangkaian langkah");
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 20));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("yang sistematis merngarah pada jawaban yang diinginkan.");
        jPanel13.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Mencari Kuadrat");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        cariKuadrat.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));
        cariKuadrat.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 470, 10));

        jLabel46.setText("Masukkan angka yang akan dicari hasil kuadratnya");
        cariKuadrat.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        cariKuadrat.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 210, 50));

        jButton2.setBackground(new java.awt.Color(0, 204, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        cariKuadrat.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel47.setText("Hasil kuadrat dari");
        cariKuadrat.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jTextField2.setEditable(false);
        cariKuadrat.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 80, 40));

        jLabel48.setText("adalah");
        cariKuadrat.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        cariKuadrat.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 70, 40));

        jButton9.setText("Cari lagi");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        cariKuadrat.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jButton17.setBackground(new java.awt.Color(255, 0, 51));
        jButton17.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("QUIT");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        cariKuadrat.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 90, -1));

        getContentPane().add(cariKuadrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 500, 420));

        barisPanel.setBackground(new java.awt.Color(255, 255, 255));
        barisPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        barisPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Menu Baris dan Deret");
        barisPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        PanelBarisDeret.setBackground(new java.awt.Color(255, 102, 102));
        PanelBarisDeret.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Barisan adalah kelompok bilangan yang berurutan");
        PanelBarisDeret.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 20));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Baris dan deret adalah selisih dua suku berurutan sama dan tetap");
        PanelBarisDeret.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Baris dan Deret");
        PanelBarisDeret.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Deret adalah jumlah dari suku-suku pada barisan");
        PanelBarisDeret.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        barisPanel.add(PanelBarisDeret, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));

        btnBarisAritmatika1.setBackground(new java.awt.Color(153, 0, 153));
        btnBarisAritmatika1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        btnBarisAritmatika1.setForeground(new java.awt.Color(255, 255, 255));
        btnBarisAritmatika1.setText("Baris Aritmatika");
        btnBarisAritmatika1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBarisAritmatika1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBarisAritmatika1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarisAritmatika1ActionPerformed(evt);
            }
        });
        barisPanel.add(btnBarisAritmatika1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 210, 50));

        btnBarisAritmatika2.setBackground(new java.awt.Color(153, 153, 0));
        btnBarisAritmatika2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        btnBarisAritmatika2.setForeground(new java.awt.Color(255, 255, 255));
        btnBarisAritmatika2.setText("Deret Aritmatika");
        btnBarisAritmatika2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBarisAritmatika2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBarisAritmatika2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarisAritmatika2ActionPerformed(evt);
            }
        });
        barisPanel.add(btnBarisAritmatika2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 210, 50));
        barisPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, -1));

        jButton18.setBackground(new java.awt.Color(255, 0, 51));
        jButton18.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("QUIT");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        barisPanel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 90, -1));

        getContentPane().add(barisPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 500, 420));

        brAritmatika.setBackground(new java.awt.Color(255, 255, 255));
        brAritmatika.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        brAritmatika.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBarisDeret1.setBackground(new java.awt.Color(0, 153, 0));
        PanelBarisDeret1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Un = a + (n-1)b");
        PanelBarisDeret1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 20));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Baris Aritmatika");
        PanelBarisDeret1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Rumus :");
        PanelBarisDeret1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        brAritmatika.add(PanelBarisDeret1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 100));
        brAritmatika.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 450, -1));

        jLabel54.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel54.setText("Hasilnya adalah");
        brAritmatika.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        tfHasilnya.setEditable(false);
        tfHasilnya.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tfHasilnya.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfHasilnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHasilnyaActionPerformed(evt);
            }
        });
        brAritmatika.add(tfHasilnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        jLabel55.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel55.setText(":");
        brAritmatika.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 30, 20));

        tfNilai.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tfNilai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNilai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNilaiActionPerformed(evt);
            }
        });
        brAritmatika.add(tfNilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 100, 40));

        jLabel56.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel56.setText("Masukkan beda (b)");
        brAritmatika.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        tfBeda.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tfBeda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBeda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfBeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBedaActionPerformed(evt);
            }
        });
        brAritmatika.add(tfBeda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 100, 40));

        jLabel57.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel57.setText("Masukkan nilai awal (a)");
        brAritmatika.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel58.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel58.setText(":");
        brAritmatika.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 30, 20));

        jLabel59.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel59.setText(":");
        brAritmatika.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 30, 20));

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        brAritmatika.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 80, 30));

        jButton11.setBackground(new java.awt.Color(0, 204, 204));
        jButton11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Submit");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        brAritmatika.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 80, 30));

        tfElemen.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tfElemen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfElemen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfElemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfElemenActionPerformed(evt);
            }
        });
        brAritmatika.add(tfElemen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 100, 40));

        jLabel61.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel61.setText(":");
        brAritmatika.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 30, 20));

        jLabel60.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel60.setText("Masukkan jumlah elemen (n)");
        brAritmatika.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jButton19.setBackground(new java.awt.Color(255, 0, 51));
        jButton19.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("QUIT");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        brAritmatika.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 90, -1));

        getContentPane().add(brAritmatika, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 500, 420));

        drAritmatika.setBackground(new java.awt.Color(255, 255, 255));
        drAritmatika.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        drAritmatika.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setBackground(new java.awt.Color(255, 0, 51));
        jButton12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("QUIT");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        drAritmatika.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 80, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel51.setText("Mencari Deret Aritmatika");
        drAritmatika.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        PanelBarisDeret2.setBackground(new java.awt.Color(204, 153, 0));
        PanelBarisDeret2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Un = a (n-1) b");
        PanelBarisDeret2.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, 20));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Deret Aritmatika");
        PanelBarisDeret2.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Rumus :");
        PanelBarisDeret2.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Sn = n/2 (a+Un)");
        PanelBarisDeret2.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, 20));

        drAritmatika.add(PanelBarisDeret2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 100));
        drAritmatika.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 450, -1));

        jLabel65.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel65.setText("Hasilnya adalah");
        drAritmatika.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        tfHasilnya1.setEditable(false);
        tfHasilnya1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tfHasilnya1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfHasilnya1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHasilnya1ActionPerformed(evt);
            }
        });
        drAritmatika.add(tfHasilnya1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 270, 40));

        jLabel66.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel66.setText(":");
        drAritmatika.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 30, 20));

        tfNilai3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tfNilai3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNilai3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNilai3ActionPerformed(evt);
            }
        });
        drAritmatika.add(tfNilai3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 100, 40));

        jLabel67.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel67.setText("Masukkan beda (b)");
        drAritmatika.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        tfBeda1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tfBeda1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBeda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBeda1ActionPerformed(evt);
            }
        });
        drAritmatika.add(tfBeda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 100, 40));

        jLabel68.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel68.setText("Masukkan nilai awal (a)");
        drAritmatika.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel69.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel69.setText(":");
        drAritmatika.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 30, 20));

        jLabel70.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel70.setText(":");
        drAritmatika.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 30, 20));
        drAritmatika.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 230, -1));

        jButton13.setBackground(new java.awt.Color(204, 0, 102));
        jButton13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Clear");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        drAritmatika.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 80, 30));

        jButton14.setBackground(new java.awt.Color(255, 153, 0));
        jButton14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Submit");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        drAritmatika.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 80, 30));

        tfElemen1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tfElemen1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfElemen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfElemen1ActionPerformed(evt);
            }
        });
        drAritmatika.add(tfElemen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 100, 40));

        jLabel71.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel71.setText(":");
        drAritmatika.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 30, 20));

        jLabel72.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel72.setText("Masukkan jumlah elemen (n)");
        drAritmatika.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        drAritmatika.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 450, 20));

        getContentPane().add(drAritmatika, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 500, 420));

        probabilitasPanel.setBackground(new java.awt.Color(255, 255, 255));
        probabilitasPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        probabilitasPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        probabilitasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Algoritma merupakan prosedur yang mengikuti serangkaian langkah");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 20));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("yang sistematis merngarah pada jawaban yang diinginkan.");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Probabilitas");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        probabilitasPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));

        jLabel42.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel42.setText("Jumlah Kejadian");
        probabilitasPanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        tfJumlahKejadian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfJumlahKejadian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahKejadianActionPerformed(evt);
            }
        });
        probabilitasPanel.add(tfJumlahKejadian, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 40));

        tfJumlahPercobaan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfJumlahPercobaan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahPercobaan1ActionPerformed(evt);
            }
        });
        probabilitasPanel.add(tfJumlahPercobaan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 40));

        jLabel43.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel43.setText(":");
        probabilitasPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel44.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel44.setText("Jumlah Percobaan");
        probabilitasPanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel45.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel45.setText(":");
        probabilitasPanel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 20, -1));
        probabilitasPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 460, -1));

        btnHitung.setBackground(new java.awt.Color(0, 204, 204));
        btnHitung.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("Hitung");
        btnHitung.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHitung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        probabilitasPanel.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 60, 30));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setText("Hasilnya adalah :");
        probabilitasPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        tfHasilPrb.setEditable(false);
        tfHasilPrb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfHasilPrb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfHasilPrb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfHasilPrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHasilPrbActionPerformed(evt);
            }
        });
        probabilitasPanel.add(tfHasilPrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 290, 40));

        jButton20.setBackground(new java.awt.Color(255, 0, 51));
        jButton20.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("QUIT");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        probabilitasPanel.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 90, -1));

        btnHitung1.setBackground(new java.awt.Color(0, 204, 204));
        btnHitung1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnHitung1.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung1.setText("Hitung");
        btnHitung1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHitung1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHitung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitung1ActionPerformed(evt);
            }
        });
        probabilitasPanel.add(btnHitung1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 60, 30));

        jButton6.setBackground(new java.awt.Color(0, 51, 255));
        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Clear");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        probabilitasPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 60, 30));

        getContentPane().add(probabilitasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 500, 420));

        profilPanel.setBackground(new java.awt.Color(255, 255, 255));
        profilPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        profilPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("2305005");
        profilPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Kami dari kelompok 2 dengan Tema Kelompok adalah Algoritma");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("PROFIL");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        profilPanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 90));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel49.setText("Indri Rahmawati");
        profilPanel.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel73.setText("Ayu Permata Sari");
        profilPanel.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel74.setText("2310302");
        profilPanel.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel75.setText("Junaedi");
        profilPanel.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel76.setText("2301686");
        profilPanel.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel77.setText("Fathinah Izzati");
        profilPanel.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel78.setText("2309706");
        profilPanel.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));
        profilPanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 330, 10));
        profilPanel.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 330, 10));
        profilPanel.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 330, 10));
        profilPanel.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 330, 10));

        jButton15.setBackground(new java.awt.Color(255, 0, 51));
        jButton15.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("QUIT");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        profilPanel.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 80, -1));

        getContentPane().add(profilPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 500, 420));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11_Science (1).jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void bubbleSort(int[] array) {
        int n = array.length;
        boolean swapped;
        for (int i = 0; i < n - 1; i++) {
            swapped = false;
            for (int j = 0; j < n - 1 - i; j++) {
                if (array[j] > array[j + 1]) {
                    // Swap array[j] and array[j + 1]
                    int temp = array[j];
                    array[j] = array[j + 1];
                    array[j + 1] = temp;
                    swapped = true;
                }
            }
            if (!swapped) break;
        }
    }
    private void cariKuadrat_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariKuadrat_btnActionPerformed
        // Goes to Mencari Kuadrat
        profilPanel.setVisible(false);
        AlgoPanel.setVisible(false);
        barisPanel.setVisible(false);
        probabilitasPanel.setVisible(false);
        bubblesort_algo.setVisible(false);
        eucledian.setVisible(false);
        cariKuadrat.setVisible(true);
        brAritmatika.setVisible(false);
        drAritmatika.setVisible(false);
    }//GEN-LAST:event_cariKuadrat_btnActionPerformed

    private void bubblesort_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubblesort_btnActionPerformed
        // Goes to Sorting Java bubblesort
        profilPanel.setVisible(false);
        AlgoPanel.setVisible(false);
        barisPanel.setVisible(false);
        probabilitasPanel.setVisible(false);
        bubblesort_algo.setVisible(true);
        eucledian.setVisible(false);
        cariKuadrat.setVisible(false);
        brAritmatika.setVisible(false);
        drAritmatika.setVisible(false);
    }//GEN-LAST:event_bubblesort_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Exit the program
        
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // algoritma eucledian
        profilPanel.setVisible(false);
        AlgoPanel.setVisible(false);
        barisPanel.setVisible(false);
        probabilitasPanel.setVisible(false);
        bubblesort_algo.setVisible(false);
        eucledian.setVisible(true);
        cariKuadrat.setVisible(false);
        brAritmatika.setVisible(false);
        drAritmatika.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // mouse pressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // mouse dragged
        int x = evt.getX();
        int y = evt.getY();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // Panel Algoritma
        setColor(jPanel3);
        resetColor(jPanel6);
        resetColor(jPanel7);
        resetColor(jPanel8);
        AlgoPanel.setVisible(true);
        barisPanel.setVisible(false);
        probabilitasPanel.setVisible(false);
        profilPanel.setVisible(false);
        bubblesort_algo.setVisible(false);
        eucledian.setVisible(false);
        cariKuadrat.setVisible(false);
        brAritmatika.setVisible(false);
        drAritmatika.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // jPanel baris dan deret
        setColor(jPanel6);
        resetColor(jPanel3);
        resetColor(jPanel7);
        resetColor(jPanel8);
        barisPanel.setVisible(true);
        AlgoPanel.setVisible(false);
        probabilitasPanel.setVisible(false);
        profilPanel.setVisible(false);
        bubblesort_algo.setVisible(false);
        eucledian.setVisible(false);
        cariKuadrat.setVisible(false);
        brAritmatika.setVisible(false);
        drAritmatika.setVisible(false);

    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // jPanel probabilitas
        setColor(jPanel7);
        resetColor(jPanel3);
        resetColor(jPanel6);
        resetColor(jPanel8);
        probabilitasPanel.setVisible(true);
        AlgoPanel.setVisible(false);
        barisPanel.setVisible(false);
        profilPanel.setVisible(false);
        bubblesort_algo.setVisible(false);
        eucledian.setVisible(false);
        cariKuadrat.setVisible(false);
        brAritmatika.setVisible(false);
        drAritmatika.setVisible(false);

    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // jPanel Profil
        setColor(jPanel8);
        resetColor(jPanel3);
        resetColor(jPanel7);
        resetColor(jPanel6);
        profilPanel.setVisible(true);
        AlgoPanel.setVisible(false);
        barisPanel.setVisible(false);
        probabilitasPanel.setVisible(false);
        bubblesort_algo.setVisible(false);
        eucledian.setVisible(false);
        cariKuadrat.setVisible(false);
        brAritmatika.setVisible(false);
        drAritmatika.setVisible(false);

    }//GEN-LAST:event_jPanel8MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tfAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAngkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAngkaActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // submit button
        String input = tfAngka.getText();

        try {
            //split input into an array of strings
            String[] stringNumbers = input.split(",");
            //convert string array to integer
            int[] numbers = new int[stringNumbers.length];
            for (int i =0; i < stringNumbers.length; i++) {
                numbers[i] = Integer.parseInt(stringNumbers[i].trim());
            }
            // Perform bubble sort
            bubbleSort(numbers);

            // Build sorted number string
            StringBuilder sortedNumbers = new StringBuilder();
            for (int i = 0; i < numbers.length; i++) {
                sortedNumbers.append(numbers[i]);
                if (i < numbers.length - 1) {
                    sortedNumbers.append(", ");
                }
            }

            // Display sorted numbers
            tfHasil.setText(sortedNumbers.toString());

            // menampilkan total angka yang sudah di sort
            tfTotalAngka.setText(String.valueOf(numbers.length));

        } catch (NumberFormatException e) {
            tfHasil.setText("Input invalid. Masukkan angka yang dipisahkan dengan koma.");
            tfTotalAngka.setText("");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // button Clear
        tfAngka.setText("");
        tfHasil.setText("");
        tfTotalAngka.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void tfHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHasilActionPerformed

    private void tfNilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNilai1ActionPerformed

    private void tfNilai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNilai2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNilai2ActionPerformed

    private void btnSubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit2ActionPerformed
        // submit tombol
        int angka1 = 0;
        int angka2= 0;
        int a= 0;
        int b= 0;

        a = Integer.parseInt(tfNilai1.getText());
        b = Integer.parseInt(tfNilai2.getText());

        angka1 = Integer.parseInt(tfNilai1.getText());
        angka2 = Integer.parseInt(tfNilai2.getText());

        int temp= 0;
        while (angka2!=0){
            temp = angka2;
            angka2 = angka1 % angka2;
            angka1 = temp;
        }

        tfNilai11.setText("" + a);
        tfNilai22.setText("" + b);
        tfHasil2.setText("" + angka1);
    }//GEN-LAST:event_btnSubmit2ActionPerformed

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        // Tclear button
        tfNilai1.setText("");
        tfNilai2.setText("");
        tfHasil2.setText("");
        tfNilai11.setText("");
        tfNilai22.setText("");
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void tfNilai11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNilai11ActionPerformed
        // tf angka 1
    }//GEN-LAST:event_tfNilai11ActionPerformed

    private void tfNilai22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNilai22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNilai22ActionPerformed

    private void tfHasil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHasil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHasil2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Cari hasil kuadrat
        int jawaban;

        jawaban=Integer.parseInt(jTextField1.getText());
        int hasil = jawaban * jawaban;

        jTextField2.setText(""+ jawaban);
        jTextField3.setText(""+ hasil);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // Cari kuadrat lagi
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnBarisAritmatika1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarisAritmatika1ActionPerformed
        // btn baris aritmatika
        profilPanel.setVisible(false);
        AlgoPanel.setVisible(false);
        barisPanel.setVisible(false);
        probabilitasPanel.setVisible(false);
        bubblesort_algo.setVisible(false);
        eucledian.setVisible(false);
        cariKuadrat.setVisible(false);
        brAritmatika.setVisible(true);
        drAritmatika.setVisible(false);
    }//GEN-LAST:event_btnBarisAritmatika1ActionPerformed

    private void tfJumlahKejadianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahKejadianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahKejadianActionPerformed

    private void tfJumlahPercobaan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahPercobaan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahPercobaan1ActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // hitung hasil
        try {
            int percobaan = Integer.parseInt(tfJumlahPercobaan1.getText().trim());
            int kejadian = Integer.parseInt(tfJumlahKejadian.getText().trim());
            
            if (percobaan <= 0 || kejadian < 0 || kejadian > percobaan) {
                tfHasilPrb.setText("Input tidak valid.");
                return;
            }
            double probabilitas = (double) kejadian / percobaan;
            
            //memberikan hasil
            tfHasilPrb.setText(String.format("%.2f", probabilitas));
        } catch (NumberFormatException e) {
            tfHasilPrb.setText("Input tidak valid.");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void tfHasilPrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHasilPrbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHasilPrbActionPerformed

    private void tfHasilnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHasilnyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHasilnyaActionPerformed

    private void tfNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNilaiActionPerformed

    private void tfBedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBedaActionPerformed

    private void tfElemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfElemenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfElemenActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // submit button
        try {
            // Get input values
            int nilaiAwal = Integer.parseInt(tfNilai.getText().trim());
            int beda = Integer.parseInt(tfBeda.getText().trim());
            int jumlahElemen = Integer.parseInt(tfElemen.getText().trim());

            // Validate input
            if (jumlahElemen <= 0) {
                tfHasilnya.setText("Jumlah elemen harus lebih dari 0.");
                return;
            }

            // Calculate arithmetic sequence
            StringBuilder hasil = new StringBuilder();
            for (int i = 0; i < jumlahElemen; i++) {
                int nilai = nilaiAwal + i * beda;
                hasil.append(nilai).append(i < jumlahElemen - 1 ? ", " : "");
            }

            // Display result
            tfHasilnya.setText(hasil.toString());
        } catch (NumberFormatException e) {
            tfHasilnya.setText("Input tidak valid. Masukkan angka yang benar.");
        }
    
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // clear btn
        tfNilai.setText("");
        tfBeda.setText("");
        tfElemen.setText("");
        tfHasilnya.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBarisAritmatika2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarisAritmatika2ActionPerformed
        // dr aritmatika
        profilPanel.setVisible(false);
        AlgoPanel.setVisible(false);
        barisPanel.setVisible(false);
        probabilitasPanel.setVisible(false);
        bubblesort_algo.setVisible(false);
        eucledian.setVisible(false);
        cariKuadrat.setVisible(false);
        brAritmatika.setVisible(false);
        drAritmatika.setVisible(true);
    }//GEN-LAST:event_btnBarisAritmatika2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void tfHasilnya1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHasilnya1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHasilnya1ActionPerformed

    private void tfNilai3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNilai3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNilai3ActionPerformed

    private void tfBeda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBeda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBeda1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // clear
        tfNilai3.setText("");
        tfBeda1.setText("");
        tfElemen1.setText("");
        tfHasilnya1.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // submit deret aritmatika
         try {
            // Get input values
            int nilaiAwal = Integer.parseInt(tfNilai3.getText().trim());
            int beda = Integer.parseInt(tfBeda1.getText().trim());
            int jumlahElemen = Integer.parseInt(tfElemen1.getText().trim());

            // Validate input
            if (jumlahElemen <= 0) {
                tfHasilnya1.setText("Jumlah elemen harus lebih dari 0.");
                return;
            }

            // Calculate arithmetic series
            StringBuilder hasil = new StringBuilder();
            int sum = 0;
            for (int i = 0; i < jumlahElemen; i++) {
                int nilai = nilaiAwal + i * beda;
                sum += nilai;
                hasil.append(nilai).append(i < jumlahElemen - 1 ? ", " : "");
            }

            // Display result
            tfHasilnya1.setText("" + hasil.toString() + "\nJumlah: " + sum);
        } catch (NumberFormatException e) {
            tfHasilnya1.setText("Input tidak valid. Masukkan angka yang benar.");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void tfElemen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfElemen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfElemen1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnHitung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitung1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitung1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        tfJumlahPercobaan1.setText("");
        tfJumlahKejadian.setText("");
        tfHasilPrb.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    void setColor(JPanel panel){
        panel.setBackground(new Color(88,122,224));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(77,108,202));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlgoPanel;
    private javax.swing.JPanel PanelBarisDeret;
    private javax.swing.JPanel PanelBarisDeret1;
    private javax.swing.JPanel PanelBarisDeret2;
    private javax.swing.JPanel barisPanel;
    private javax.swing.JPanel brAritmatika;
    private javax.swing.JButton btnBarisAritmatika1;
    private javax.swing.JButton btnBarisAritmatika2;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHitung1;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmit2;
    private javax.swing.JPanel bubblesort_algo;
    private javax.swing.JButton bubblesort_btn;
    private javax.swing.JPanel cariKuadrat;
    private javax.swing.JButton cariKuadrat_btn;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel drAritmatika;
    private javax.swing.JPanel eucledian;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel probabilitasPanel;
    private javax.swing.JPanel profilPanel;
    private javax.swing.JTextField tfAngka;
    private javax.swing.JTextField tfBeda;
    private javax.swing.JTextField tfBeda1;
    private javax.swing.JTextField tfElemen;
    private javax.swing.JTextField tfElemen1;
    private javax.swing.JTextField tfHasil;
    private javax.swing.JTextField tfHasil2;
    private javax.swing.JTextField tfHasilPrb;
    private javax.swing.JTextField tfHasilnya;
    private javax.swing.JTextField tfHasilnya1;
    private javax.swing.JTextField tfJumlahKejadian;
    private javax.swing.JTextField tfJumlahPercobaan1;
    private javax.swing.JTextField tfNilai;
    private javax.swing.JTextField tfNilai1;
    private javax.swing.JTextField tfNilai11;
    private javax.swing.JTextField tfNilai2;
    private javax.swing.JTextField tfNilai22;
    private javax.swing.JTextField tfNilai3;
    private javax.swing.JTextField tfTotalAngka;
    // End of variables declaration//GEN-END:variables
}
